# Generated by Django 3.2 on 2021-05-28 13:40

import basic_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_url', models.URLField(blank=1)),
                ('prof_img', models.ImageField(blank=1, upload_to='')),
                ('user', models.OneToOneField(on_delete=basic_app.models.nothin, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
