# Generated by Django 3.2 on 2021-05-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prof_img',
            field=models.ImageField(blank=1, upload_to='user_pics'),
        ),
    ]
